### PR TITLE
[WIP] PHP 7 compatibility

### PR DESCRIPTION
**Pull request by asgrim**

### CODE REVIEW

**Comment by derickr** [comment]
Did you ever finish this?

**Comment by asgrim** [comment]
No, sadly this was as far as I got with it :/

**Comment by elstamey** [comment]
Is there a to-do list of what remains?

**Comment by asgrim** [comment]
Sorry, afraid not; it's been a while but if I remember correctly I was mid-way through just fixing compiler issues (e.g. function call signature changes and whatnot) as they come up.

**Comment by asgrim** [comment]
Happy for someone else to take over this branch though!

**Comment by derickr** [comment]
Closing in favour of PR #4

**Pull request closed without merging**
