### PR TITLE
PHP 7 support

### PR DESCRIPTION
**Pull request by Maners**
Hello,

This pull is based on the work started here:
https://github.com/derickr/pecl-dbus/pull/2

Verified to work on PHP 7.1.9 and PHP 5.6.30, by

* compile testing in both environments
* running (in both environments) the following examples from the examples dir and cross-checked with git master for regressions:
** examples/add-system-connection.php
** examples/request-name.php
** examples/call-multiple-returns.php
** examples/call-array-dict-variant.php
** examples/call-introspect.php (broken, on master as well so not regression from the port itself)
** examples/call-variant-dict.php (broken, on master too)
** examples/server-empty-interface.php
** examples/call-empty-interface.php
** examples/call-non-registered-class.php
** examples/signal-watch.php
** examples/signal-send.php (does not seem to work, same behavior as on master)

### CODE REVIEW

**Comment by stefansaraev** [comment]
@derickr any plans for this?

**Comment by derickr** [comment]
I totally missed this... Does the code in the Pull Request work @stefansaraev ?

**Comment by stefansaraev** [comment]
@derickr we are using it (with an important minor fix, that may break php5, idk.. see my commit referenced above) on at least 5 or 6 brandmeister servers - debian stretch / php 7.0, but I've been told php7.1 and php7.2 are also working.

**Comment by stefansaraev** [comment]
@Maners if you dont have time for this, I can PR my branch directly to @derickr 

@derickr perhaps you can create a backup php5 branch from current master, then merge and get this all tested?

**Comment by derickr** [comment]
To be honest, I don't care about PHP 5 usage any more. If there is a full PR against this, that removes PHP 5 support (and adds PHP 7 :-) ), I wouldn't be sad; and I'd be happy to merge and make a new release.

**Comment by stefansaraev** [comment]
so you prefer cleaning up the php5 ifdeffery? 

sure, I can do that.

**Comment by derickr** [comment]
Yeah, the fewer #ifdef's, the better :-) Will you be making a new PR @stefansaraev ?

**Comment by stefansaraev** [comment]
yes I will. I'll need some time to cleanup and test..

**Comment by Maners** [comment]
I don't need PHP5 support either. I'm closing this PR as @stefansaraev seems to be on top of things and I have no real life projects utilizing php-dbus anyway and I'm quite out of touch with it by now

**Pull request closed without merging**
